apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: promptcraft

resources:
  - namespace.yaml
  - minecraft/pvc.yaml
  - minecraft/deployment.yaml
  - minecraft/service.yaml
  - playit/onepassword-item.yaml
  - playit/deployment.yaml
  - bridge/onepassword-items.yaml
  - bridge/configmap.yaml
  - bridge/rbac.yaml
  - bridge/pvc.yaml
  - bridge/deployment.yaml
  - bridge/service.yaml
  - bridge/httproute.yaml
