# Скрипты сына и то, что написала модель
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bridge-scripts
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
